<?php

it('uses real output and standard formula material consumption at completion', function () {
    $source = file_get_contents(resource_path('views/admin/production-orders/show.blade.php'));

    expect($source)
        ->toContain('Manufactured Qty')
        ->toContain('name="quantity_manufactured"')
        ->toContain('Good / Actual Finished Qty')
        ->toContain('name="quantity_produced"')
        ->toContain('Rejected / Scrap Qty')
        ->toContain('name="quantity_rejected"')
        ->toContain('Actual Raw Material Consumption')
        ->toContain('name="materials[{{ $index }}][actual_quantity]"')
        ->toContain('name="materials[{{ $index }}][wastage_quantity]"')
        ->toContain('BOM remains the planned baseline')
        ->toContain('BOM Planned')
        ->toContain('Actual Consumed')
        ->toContain('Waste within Actual')
        ->toContain('Standard consumption is deducted from stock automatically.')
        ->toContain('Standard formula')
        ->toContain('Standard formula · roll paper')
        ->toContain('Use measured actual')
        ->toContain('data-auto-formula="1"')
        ->toContain('data-planned-run="{{ (float) ($material[\'planned_run_quantity\'] ?? 0) }}"')
        ->toContain('syncStandardFormulaConsumption')
        ->toContain('Automatically follows Manufactured Qty.')
        ->toContain('data-variance-target="materialVariance{{ $index }}"')
        ->toContain('Reel tracking')
        ->toContain('Use physical reel declaration')
        ->toContain('Advanced/optional. Normal production requires no reel weighing')
        ->toContain('name="materials[{{ $index }}][use_measured_actual]"')
        ->toContain('name="materials[{{ $index }}][use_reel_selection]"')
        ->toContain('[consumed_kg]')
        ->toContain('[final_remaining_kg]')
        ->toContain('Scale remainders are observational')
        ->toContain('Save Actuals & Complete Production')
        ->toContain('id="productionCompletionForm"')
        ->toContain('Materials to Reconcile')
        ->toContain('Inventory Method')
        ->toContain('FIFO Actuals')
        ->toContain('id="completionOutputCheck"')
        ->toContain('class="btn btn-outline-secondary completion-quick-action use-bom-plan"')
        ->toContain('id="completionSummaryPanel"')
        ->toContain('#completeProductionModal .completion-modal-content > form')
        ->toContain('#completeProductionModal .modal-body')
        ->toContain('overflow-y: auto')
        ->toContain('max-height: calc(100vh - 2rem)')
        ->toContain('id="completionOverCount"')
        ->toContain('id="completionBelowCount"')
        ->toContain('id="completionOnPlanCount"')
        ->toContain('Higher actual usage deducts additional FIFO stock')
        ->toContain('lower actual usage restores the unused provisional allocation')
        ->toContain('BOM remains unchanged; only actual production consumption and inventory are reconciled.')
        ->toContain('Planned vs Actual Production Variance')
        ->not->toContain('Scan / enter reel code')
        ->not->toContain('reel-scan-input')
        ->not->toContain('bi-upc-scan')
        ->not->toContain('reconcile raw-material consumption to this actual quantity');
});
