<?php

it('supports calculated paper consumption and optional manual reel reconciliation at production completion', function () {
    $source = file_get_contents(resource_path('views/admin/production-orders/show.blade.php'));

    expect($source)
        ->toContain('Manufactured Qty')
        ->toContain('name="quantity_manufactured"')
        ->toContain('Good / Actual Finished Qty')
        ->toContain('name="quantity_produced"')
        ->toContain('Rejected / Scrap Qty')
        ->toContain('name="quantity_rejected"')
        ->toContain('Material Consumption')
        ->toContain('name="materials[{{ $index }}][consumption_mode]"')
        ->toContain('System calculated')
        ->toContain('Manual actual')
        ->toContain('name="materials[{{ $index }}][actual_quantity]"')
        ->toContain('name="materials[{{ $index }}][wastage_quantity]"')
        ->toContain('Paper reels are calculated automatically from actual manufactured output')
        ->toContain('BOM remains the planned baseline')
        ->toContain('BOM Planned')
        ->toContain('Variance')
        ->toContain('data-variance-target="materialVariance{{ $index }}"')
        ->toContain('name="materials[{{ $index }}][reel_mode]"')
        ->toContain('System FIFO / continue normally')
        ->toContain('Selected reel continues on machine')
        ->toContain('Selected reel finished')
        ->toContain('Advanced / multiple reels')
        ->toContain('name="materials[{{ $index }}][selected_reel_id]"')
        ->toContain('[consumed_kg]')
        ->toContain('[final_remaining_kg]')
        ->toContain('Multiple reel details')
        ->toContain('Save Actuals & Complete Production')
        ->toContain('id="productionCompletionForm"')
        ->toContain('System calculated')
        ->toContain('Inventory impact')
        ->toContain('Roll paper defaults to calculated usage from actual manufactured output')
        ->toContain('id="completionOutputCheck"')
        ->toContain('id="completionSummaryPanel"')
        ->toContain('#completeProductionModal .completion-modal-content > form')
        ->toContain('#completeProductionModal .modal-body')
        ->toContain('overflow-y: auto')
        ->toContain('max-height: calc(100vh - 2rem)')
        ->toContain('id="completionOverCount"')
        ->toContain('id="completionBelowCount"')
        ->toContain('id="completionOnPlanCount"')
        ->toContain('If a reel continues, the balance carries forward')
        ->toContain('If a reel finishes, its full remaining ERP balance is consumed')
        ->not->toContain('Scan / enter reel code')
        ->not->toContain('reel-scan-input')
        ->not->toContain('bi-upc-scan');
});
