<?php

if (!function_exists('getFlagByCurrencyCode')) {
    function getFlagByCurrencyCode(string $code): string
    {
        $map = [
            'USD' => 'us',
            'AFN' => 'af',
            'RMB' => 'cn',
            'IRR' => 'ir',
            'PKR' => 'pk',
            'EUR' => 'eu',
            'GBP' => 'gb',
            'AED' => 'ae',
            'INR' => 'in',
            'TRY' => 'tr',
            'CAD' => 'ca',
            'AUD' => 'au',
            'SAR' => 'sa',
            'KWD' => 'kw',
            'NPR' => 'np',
            'BDT' => 'bd',
            'JPY' => 'jp',
            'CHF' => 'ch',
            'SEK' => 'se',
            'NOK' => 'no',
            'DKK' => 'dk',
            'ZAR' => 'za',
            'MYR' => 'my',
            'SGD' => 'sg',
            'THB' => 'th',
            'KRW' => 'kr',
            'IDR' => 'id',
            'EGP' => 'eg',
            'HKD' => 'hk',
            'BRL' => 'br',
            'MXN' => 'mx',
            'RUB' => 'ru',
            'ILS' => 'il',
            'CZK' => 'cz',
            'PLN' => 'pl',
            'HUF' => 'hu',
            'NGN' => 'ng',
            'VND' => 'vn',
            'TWD' => 'tw',
            'ARS' => 'ar',
            'QAR' => 'qa',
            'OMR' => 'om',
            'BHD' => 'bh',
            'LKR' => 'lk',
            'JOD' => 'jo',
            'DZD' => 'dz',
            'MAD' => 'ma',
            'LBP' => 'lb',
            'SDG' => 'sd',
            'DOP' => 'do',
            'UYU' => 'uy',
            'CLP' => 'cl',
            'PEN' => 'pe',
            'COP' => 'co',
            'KZT' => 'kz',
            'AZN' => 'az',
            'ALL' => 'al',
            'GEL' => 'ge',
            'XAF' => 'cm',
            'XOF' => 'sn',
            'ETB' => 'et',
            'TZS' => 'tz',
            'KES' => 'ke',
        ];


        $countryCode = $map[strtoupper($code)] ?? 'unknown';
        return "assets/flags/{$countryCode}.svg";
    }
}
